//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TransferInfo_AC.RECIBE_IMAGENES_AC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_RECIBEIMAGENESSoap", Namespace="http://tempuri.org/")]
    public partial class WS_RECIBEIMAGENES : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RECIBEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_RECIBEIMAGENES() {
            this.Url = global::TransferInfo_AC.Properties.Settings.Default.TransferInfo_AC_RECIBE_IMAGENES_AC_WS_RECIBEIMAGENES;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RECIBECompletedEventHandler RECIBECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RECIBE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RECIBE([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ArchivoZip, string Usuario, string Password, string idTramite, string idExpediente, string nss) {
            object[] results = this.Invoke("RECIBE", new object[] {
                        ArchivoZip,
                        Usuario,
                        Password,
                        idTramite,
                        idExpediente,
                        nss});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RECIBEAsync(byte[] ArchivoZip, string Usuario, string Password, string idTramite, string idExpediente, string nss) {
            this.RECIBEAsync(ArchivoZip, Usuario, Password, idTramite, idExpediente, nss, null);
        }
        
        /// <remarks/>
        public void RECIBEAsync(byte[] ArchivoZip, string Usuario, string Password, string idTramite, string idExpediente, string nss, object userState) {
            if ((this.RECIBEOperationCompleted == null)) {
                this.RECIBEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRECIBEOperationCompleted);
            }
            this.InvokeAsync("RECIBE", new object[] {
                        ArchivoZip,
                        Usuario,
                        Password,
                        idTramite,
                        idExpediente,
                        nss}, this.RECIBEOperationCompleted, userState);
        }
        
        private void OnRECIBEOperationCompleted(object arg) {
            if ((this.RECIBECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RECIBECompleted(this, new RECIBECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void RECIBECompletedEventHandler(object sender, RECIBECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RECIBECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RECIBECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591